name: family_connect
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter_slidable: "^0.4.7"
  flutter:
    sdk: flutter
  firebase_auth: ^0.14.0+5
    
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  file_picker: ^1.1.1
  image_picker: 0.6.1+11
  flutter_local_notifications: ^0.8.4
  dropdown_banner: ^1.4.0
  font_awesome_flutter: ^8.4.0
  folding_cell: ^0.1.2
  flutter_calendar_carousel: ^1.3.16
  flutter_auth_buttons: ^0.5.0
  random_string: ^1.1.0
  faker: ^1.1.1
  auto_size_text: ^2.1.0
  firebase_database: ^3.0.7
  cloud_firestore: ^0.12.9+4
  provider: ^3.0.0+1
  get_it: ^1.0.3+2
  firebase_storage: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/pictures/calendar.jpg
    - assets/pictures/journal.jpg
    - assets/pictures/books.jpg
    - assets/pictures/chores.jpg
    - assets/pictures/homework.jpg
    - assets/pictures/list.jpg
    - assets/pictures/achievements.jpg
    - assets/pictures/extra.jpg
    - assets/pictures/trophy.jpg
    - assets/pictures/connie.jpg
    - assets/pictures/rainbowfish.jpg
    - assets/pictures/collegekid.jpg
    - assets/pictures/daughter.jpg
    - assets/pictures/youngboy.png
    - assets/pictures/reports.jpg
    - assets/pictures/login_background.jpg
    - assets/pictures/error.png
 

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: DancingScript
      fonts:
        - asset: assets/fonts/dancing_script.ttf
    - family: Pacifico
      fonts:
        - asset: assets/fonts/pacifico.ttf
           
  
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages